default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        language_version: python3.10
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: end-of-file-fixer
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: detect-private-key
      - id: pretty-format-json
        args:
          [--autofix, --no-sort-keys, "--top-keys=_id,name,type,description"]
      - id: no-commit-to-branch
        args: [--branch, main]
        stages: [commit-msg]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--target-version, py311]
        files: ^src/.*\.py$
        exclude: ^src/dmss_api/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests]
        files: ^.*\.py$
        exclude: ^src/dmss_api/

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
        exclude: ^src/dmss_api/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: ^src/.*\.py$
        exclude: ^src/dmss_api/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        exclude: ^src/dmss_api/
        additional_dependencies:
          - types-cachetools >= 5.2.0
          - types-requests >= 2.27.30
          - types-ujson >= 5.3.0
          - types-redis >= 2.3.21.1

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^src/.*\.py$
        exclude: ^src/dmss_api/
        args:
          - "--verbose"
          - "--max-line-length=119"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503"
