repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-ast
      language_version: python3.10
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace
      exclude: ^.*\.(lock)$||^docs\/
    - id: mixed-line-ending
      exclude: ^.*\.(lock)$||^docs\/
    - id: detect-private-key

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3.10
      args: [--target-version, py310]
      files: ^src/.*\.py$

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: ^.*\.py$


- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.5
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      files: ^src/.*\.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.982'
  hooks:
    - id: mypy
      args: [--config-file=pyproject.toml]
      additional_dependencies:
        - types-cachetools >= 5.2.0
        - types-requests >= 2.27.30
        - types-ujson >= 5.3.0
        - types-redis >= 2.3.21.1


- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      files: ^src/.*\.py$
      args: [ '--max-line-length=119', '--max-complexity=18', '--select=B,C,E,F,W,T4,B9', '--ignore=E203,E266,E501,W503' ]


