version: "3.4"

services:
  dmss:
    image: datamodelingtool.azurecr.io/dmss:v1.27.1
    restart: unless-stopped
    environment:
      ENVIRONMENT: local
      REDIS_PASSWORD: maf
      MONGO_PASSWORD: maf
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs= # Don't reuse this in production...
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: bitnami/mongodb:6.0.9
    environment:
      MONGODB_ROOT_PASSWORD: maf
      MONGODB_ROOT_USER: maf
      MONGODB_EXTRA_FLAGS: "--quiet"

  job-api:
    build:
      context: .
    image: datamodelingtool.azurecr.io/dm-job
    restart: unless-stopped
    environment:
      MONGO_PASSWORD: maf
      ENVIRONMENT: azure
      SCHEDULER_ENVS_TO_EXPORT: "PUBLIC_DMSS_API,SIMA_LICENSE"
      SCHEDULER_REDIS_HOST: redis
      SCHEDULER_REDIS_PASSWORD: maf
      SCHEDULER_REDIS_PORT: 6379
      SCHEDULER_REDIS_SSL: "false"
      DMSS_API: http://dmss:5000
    depends_on:
      - redis
    ports:
      - "5001:5000"


  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: maf
