version: "3.4"

services:
  job-api:
    build:
      target: development
    image: datamodelingtool.azurecr.io/dm-job:dev
    volumes:
      - ./src/:/code/src
      - ./app/:/code/app
      - ./pyproject.toml:/code/pyproject.toml
      - ./job_plugins/:/code/src/job/handler_plugins/
      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker-in-docker jobs
      # - ../data-modelling-storage-service/gen/dmss_api:/dmss_api
    environment:
      ENVIRONMENT: local
#      AZURE_JOB_SUBSCRIPTION: 14d57366-b2ae-4da8-8b75-e273c6fdabe2
#      AZURE_JOB_RESOURCE_GROUP: dmt-test-containers
#      AZURE_SP_SECRET: ${AZURE_SP_SECRET}
#      AZURE_JOB_TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
#      AZURE_JOB_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
      #SIMA_LICENSE: |

#  db-ui:
#    image: mongo-express:1.0.0-alpha
#    restart: unless-stopped
#    ports:
#      - "8082:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: db
#      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
#      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
