# flake8: noqa

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from dmss_api.api_client import ApiClient

# import Configuration
from dmss_api.configuration import Configuration

# import exceptions
from dmss_api.exceptions import OpenApiException
from dmss_api.exceptions import ApiAttributeError
from dmss_api.exceptions import ApiTypeError
from dmss_api.exceptions import ApiValueError
from dmss_api.exceptions import ApiKeyError
from dmss_api.exceptions import ApiException
