on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  set-tag-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - id: create-ref
        run: |
          TAG_REF=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "tag-ref=$TAG_REF" >> $GITHUB_OUTPUT
    outputs:
      tag-ref: ${{ steps.create-ref.outputs.tag-ref }}

  publish-tag-ref:
    needs: [set-tag-ref, tests]
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: ${{ needs.set-tag-ref.outputs.tag-ref }}
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}


